//
// Created by Harikeshav R on 11/19/24.
//

#ifndef CONSTANTS_H
#define CONSTANTS_H

// #define STATISTICS_MENU_IMAGE_FILE_PATH "assets/menus/statistics_menu.png"


// MAIN MENU

#define MAIN_MENU_IMAGE_FILE_PATH "assets/menus/main_menu.png"

// Define details of the play button on the main menu
#define MAIN_MENU_PLAY_BUTTON_X_COORDINATE 25
#define MAIN_MENU_PLAY_BUTTON_Y_COORDINATE 135
#define MAIN_MENU_PLAY_BUTTON_X_SIZE 130
#define MAIN_MENU_PLAY_BUTTON_Y_SIZE 20

// Define details of the instructions button on the main menu
#define MAIN_MENU_INSTRUCTIONS_BUTTON_X_COORDINATE 165
#define MAIN_MENU_INSTRUCTIONS_BUTTON_Y_COORDINATE 135
#define MAIN_MENU_INSTRUCTIONS_BUTTON_X_SIZE 130
#define MAIN_MENU_INSTRUCTIONS_BUTTON_Y_SIZE 20

// Define details of the controls button on the main menu
#define MAIN_MENU_CONTROLS_BUTTON_X_COORDINATE 25
#define MAIN_MENU_CONTROLS_BUTTON_Y_COORDINATE 165
#define MAIN_MENU_CONTROLS_BUTTON_X_SIZE 130
#define MAIN_MENU_CONTROLS_BUTTON_Y_SIZE 20

// Define details of the statistics button on the main menu
#define MAIN_MENU_STATISTICS_BUTTON_X_COORDINATE 165
#define MAIN_MENU_STATISTICS_BUTTON_Y_COORDINATE 165
#define MAIN_MENU_STATISTICS_BUTTON_X_SIZE 130
#define MAIN_MENU_STATISTICS_BUTTON_Y_SIZE 20

// Define details of the credits button on the main menu
#define MAIN_MENU_CREDITS_BUTTON_X_COORDINATE 25
#define MAIN_MENU_CREDITS_BUTTON_Y_COORDINATE 195
#define MAIN_MENU_CREDITS_BUTTON_X_SIZE 130
#define MAIN_MENU_CREDITS_BUTTON_Y_SIZE 20

// Define details of the quit button on the main menu
#define MAIN_MENU_QUIT_BUTTON_X_COORDINATE 165
#define MAIN_MENU_QUIT_BUTTON_Y_COORDINATE 195
#define MAIN_MENU_QUIT_BUTTON_X_SIZE 130
#define MAIN_MENU_QUIT_BUTTON_Y_SIZE 20


// INSTRUCTIONS MENU

#define INSTRUCTIONS_MENU_IMAGE_FILE_PATH "assets/menus/instructions_menu.png"

// Define instructions menu back button dimensions
#define INSTRUCTIONS_MENU_BACK_BUTTON_X_COORDINATE 110
#define INSTRUCTIONS_MENU_BACK_BUTTON_Y_COORDINATE 196
#define INSTRUCTIONS_MENU_BACK_BUTTON_X_SIZE 100
#define INSTRUCTIONS_MENU_BACK_BUTTON_Y_SIZE 20


// CONTROLS MENU

#define CONTROLS_MENU_IMAGE_FILE_PATH "assets/menus/controls_menu.png"

// Define controls menu back button dimensions
#define CONTROLS_MENU_BACK_BUTTON_X_COORDINATE 110
#define CONTROLS_MENU_BACK_BUTTON_Y_COORDINATE 196
#define CONTROLS_MENU_BACK_BUTTON_X_SIZE 100
#define CONTROLS_MENU_BACK_BUTTON_Y_SIZE 20


// CREDITS MENU

// Define credits menu frame constants
#define CREDITS_MENU_VIDEO_NUMBER_OF_FRAMES 224
#define CREDITS_MENU_VIDEO_FRAME_RATE 30
#define CREDITS_MENU_VIDEO_FRAMES_PATH "assets/menus/credits/"

// Define credits menu back button dimensions
#define CREDITS_MENU_BACK_BUTTON_X_COORDINATE 110
#define CREDITS_MENU_BACK_BUTTON_Y_COORDINATE 208.4
#define CREDITS_MENU_BACK_BUTTON_X_SIZE 100
#define CREDITS_MENU_BACK_BUTTON_Y_SIZE 20


// QUIT MENU

#define QUIT_MENU_IMAGE_FILE_PATH "assets/menus/quit_menu.png"

// Define details of the stay button on the quit menu
#define QUIT_MENU_STAY_BUTTON_X_COORDINATE 110
#define QUIT_MENU_STAY_BUTTON_Y_COORDINATE 132.8
#define QUIT_MENU_STAY_BUTTON_X_SIZE 100
#define QUIT_MENU_STAY_BUTTON_Y_SIZE 20

// Define details of the quit button on the quit menu
#define QUIT_MENU_QUIT_BUTTON_X_COORDINATE 110
#define QUIT_MENU_QUIT_BUTTON_Y_COORDINATE 165.8
#define QUIT_MENU_QUIT_BUTTON_X_SIZE 100
#define QUIT_MENU_QUIT_BUTTON_Y_SIZE 20

#endif //CONSTANTS_H
