//
// Created by Harikeshav R on 11/19/24.
//

#ifndef CONSTANTS_H
#define CONSTANTS_H


// MAIN MENU

#define MAIN_MENU_IMAGE_FILE_PATH "assets/menus/main_menu.png"

// Define details of the play game button on the main menu
#define MAIN_MENU_PLAY_GAME_BUTTON_X_COORDINATE 65
#define MAIN_MENU_PLAY_GAME_BUTTON_Y_COORDINATE 160
#define MAIN_MENU_PLAY_GAME_BUTTON_X_SIZE 90
#define MAIN_MENU_PLAY_GAME_BUTTON_Y_SIZE 15

// Define details of the instructions button on the main menu
#define MAIN_MENU_INSTRUCTIONS_BUTTON_X_COORDINATE 165
#define MAIN_MENU_INSTRUCTIONS_BUTTON_Y_COORDINATE 160
#define MAIN_MENU_INSTRUCTIONS_BUTTON_X_SIZE 90
#define MAIN_MENU_INSTRUCTIONS_BUTTON_Y_SIZE 15

// Define details of the controls button on the main menu
#define MAIN_MENU_CONTROLS_BUTTON_X_COORDINATE 65
#define MAIN_MENU_CONTROLS_BUTTON_Y_COORDINATE 185
#define MAIN_MENU_CONTROLS_BUTTON_X_SIZE 90
#define MAIN_MENU_CONTROLS_BUTTON_Y_SIZE 15

// Define details of the statistics button on the main menu
#define MAIN_MENU_STATISTICS_BUTTON_X_COORDINATE 165
#define MAIN_MENU_STATISTICS_BUTTON_Y_COORDINATE 185
#define MAIN_MENU_STATISTICS_BUTTON_X_SIZE 90
#define MAIN_MENU_STATISTICS_BUTTON_Y_SIZE 15

// Define details of the credits button on the main menu
#define MAIN_MENU_CREDITS_BUTTON_X_COORDINATE 65
#define MAIN_MENU_CREDITS_BUTTON_Y_COORDINATE 210
#define MAIN_MENU_CREDITS_BUTTON_X_SIZE 90
#define MAIN_MENU_CREDITS_BUTTON_Y_SIZE 15

// Define details of the quit button on the main menu
#define MAIN_MENU_QUIT_BUTTON_X_COORDINATE 165
#define MAIN_MENU_QUIT_BUTTON_Y_COORDINATE 210
#define MAIN_MENU_QUIT_BUTTON_X_SIZE 90
#define MAIN_MENU_QUIT_BUTTON_Y_SIZE 15


// PLAY GAME MENU

#define PLAY_GAME_MENU_IMAGE_FILE_PATH "assets/menus/play_game_menu.png"

// Define play game menu back button dimensions
#define PLAY_GAME_MENU_BACK_BUTTON_X_COORDINATE 110
#define PLAY_GAME_MENU_BACK_BUTTON_Y_COORDINATE 196
#define PLAY_GAME_MENU_BACK_BUTTON_X_SIZE 100
#define PLAY_GAME_MENU_BACK_BUTTON_Y_SIZE 20


// INSTRUCTIONS MENU

#define INSTRUCTIONS_MENU_IMAGE_FILE_PATH "assets/menus/instructions_menu.png"

// Define instructions menu back button dimensions
#define INSTRUCTIONS_MENU_BACK_BUTTON_X_COORDINATE 115
#define INSTRUCTIONS_MENU_BACK_BUTTON_Y_COORDINATE 200
#define INSTRUCTIONS_MENU_BACK_BUTTON_X_SIZE 90
#define INSTRUCTIONS_MENU_BACK_BUTTON_Y_SIZE 15


// CONTROLS MENU

#define CONTROLS_MENU_IMAGE_FILE_PATH "assets/menus/controls_menu.png"

// Define controls menu back button dimensions
#define CONTROLS_MENU_BACK_BUTTON_X_COORDINATE 115
#define CONTROLS_MENU_BACK_BUTTON_Y_COORDINATE 200
#define CONTROLS_MENU_BACK_BUTTON_X_SIZE 90
#define CONTROLS_MENU_BACK_BUTTON_Y_SIZE 15


// STATISTICS MENU

#define STATISTICS_MENU_IMAGE_FILE_PATH "assets/menus/statistics_menu.png"

// Define controls menu back button dimensions
#define STATISTICS_MENU_BACK_BUTTON_X_COORDINATE 115
#define STATISTICS_MENU_BACK_BUTTON_Y_COORDINATE 200
#define STATISTICS_MENU_BACK_BUTTON_X_SIZE 90
#define STATISTICS_MENU_BACK_BUTTON_Y_SIZE 15


// CREDITS MENU

// Define credits menu frame constants
#define CREDITS_MENU_VIDEO_NUMBER_OF_FRAMES 481
#define CREDITS_MENU_BASE_FILE_NAME "credits_"
#define CREDITS_MENU_VIDEO_FRAMES_PATH "assets/credits/"

// Define credits menu back button dimensions
#define CREDITS_MENU_BACK_BUTTON_X_COORDINATE 115
#define CREDITS_MENU_BACK_BUTTON_Y_COORDINATE 200
#define CREDITS_MENU_BACK_BUTTON_X_SIZE 90
#define CREDITS_MENU_BACK_BUTTON_Y_SIZE 15


// QUIT MENU

#define QUIT_MENU_IMAGE_FILE_PATH "assets/menus/quit_menu.png"

// Define details of the stay button on the quit menu
#define QUIT_MENU_STAY_BUTTON_X_COORDINATE 115
#define QUIT_MENU_STAY_BUTTON_Y_COORDINATE 160
#define QUIT_MENU_STAY_BUTTON_X_SIZE 90
#define QUIT_MENU_STAY_BUTTON_Y_SIZE 15

// Define details of the quit button on the quit menu
#define QUIT_MENU_QUIT_BUTTON_X_COORDINATE 115
#define QUIT_MENU_QUIT_BUTTON_Y_COORDINATE 200
#define QUIT_MENU_QUIT_BUTTON_X_SIZE 90
#define QUIT_MENU_QUIT_BUTTON_Y_SIZE 15


// FONT

#define FONT_NUMBER_BASE_FILE_NAME "number_"
#define FONT_NUMBER_FILE_PATH "assets/font/numbers/"
#define FONT_NUMBER_X_SIZE 15
#define FONT_NUMBER_Y_SIZE 20


// DISPLAY SCORE
#define GAMEPLAY_SCORE_X_COORDINATE 90
#define GAMEPLAY_SCORE_Y_COORDINATE 0


// ARROWS
#define ARROWS_X_SIZE 30
#define ARROWS_Y_SIZE 30

#define LEFT_ARROW_IMAGE_FILE_PATH "assets/arrows/left_arrow.png"
#define LEFT_ARROW_START_X_COORDINATE 5
#define LEFT_ARROW_START_Y_COORDINATE 200
#define LEFT_ARROW_END_X_COORDINATE 5
#define LEFT_ARROW_END_Y_COORDINATE 30

#define UP_ARROW_IMAGE_FILE_PATH "assets/arrows/up_arrow.png"
#define UP_ARROW_START_X_COORDINATE 45
#define UP_ARROW_START_Y_COORDINATE 200
#define UP_ARROW_END_X_COORDINATE 45
#define UP_ARROW_END_Y_COORDINATE 30

#define DOWN_ARROW_IMAGE_FILE_PATH "assets/arrows/down_arrow.png"
#define DOWN_ARROW_START_X_COORDINATE 85
#define DOWN_ARROW_START_Y_COORDINATE 200
#define DOWN_ARROW_END_X_COORDINATE 85
#define DOWN_ARROW_END_Y_COORDINATE 30

#define RIGHT_ARROW_IMAGE_FILE_PATH "assets/arrows/right_arrow.png"
#define RIGHT_ARROW_START_X_COORDINATE 125
#define RIGHT_ARROW_START_Y_COORDINATE 200
#define RIGHT_ARROW_END_X_COORDINATE 125
#define RIGHT_ARROW_END_Y_COORDINATE 30


// MAIN GAME

#define RANDOM_TIME_DELAY_GENERATOR_START_BOUND 30
#define RANDOM_TIME_DELAY_GENERATOR_END_BOUND 50

#define ARROW_MAX_VELOCITY 10
#define ARROW_VELOCITY_CHANGE_DELAY_LOOPS 600

// DANCE

#define DANCE_FRAME_X_COORDINATE 160
#define DANCE_FRAME_Y_COORDINATE 40

#define DANCE_ITERATIONS_BETWEEN_FRAMES 12

#define DANCE_FRAMES_PATH "assets/dance/"

#define DANCE_LEFT_BASE_FILE_NAME "dance_left_"
#define DANCE_LEFT_NUMBER_OF_FRAMES 3

#define DANCE_UP_BASE_FILE_NAME "dance_forward_"
#define DANCE_UP_NUMBER_OF_FRAMES 3

#define DANCE_DOWN_BASE_FILE_NAME "dance_back_"
#define DANCE_DOWN_NUMBER_OF_FRAMES 3

#define DANCE_RIGHT_BASE_FILE_NAME "dance_right_"
#define DANCE_RIGHT_NUMBER_OF_FRAMES 3

#define DANCE_SITTING_BASE_FILE_NAME "dance_sitting_"
#define DANCE_SITTING_NUMBER_OF_FRAMES 5

#define DANCE_STANDING_BASE_FILE_NAME "dance_standing_"
#define DANCE_STANDING_NUMBER_OF_FRAMES 4

#endif //CONSTANTS_H
